/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


@interface RuntimeError : NSException <NSCoding> {
  int32_t __errornumber;
  NSString * __message;

  BOOL __errornumber_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errornumber, setter=setErrornumber:) int32_t errornumber;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithErrornumber: (int32_t) errornumber message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) errornumber;
- (void) setErrornumber: (int32_t) errornumber;
#endif
- (BOOL) errornumberIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface Driver : NSObject <NSCoding> {
  int64_t __driverid;
  int64_t __mobile;
  NSString * __name;
  int32_t __score;
  double __longitude;
  double __latitude;
  NSString * __drivercard;
  int32_t __driveage;
  NSString * __province;
  int32_t __drivercount;
  int32_t __state;
  NSData * __picture;
  int32_t __pictype;

  BOOL __driverid_isset;
  BOOL __mobile_isset;
  BOOL __name_isset;
  BOOL __score_isset;
  BOOL __longitude_isset;
  BOOL __latitude_isset;
  BOOL __drivercard_isset;
  BOOL __driveage_isset;
  BOOL __province_isset;
  BOOL __drivercount_isset;
  BOOL __state_isset;
  BOOL __picture_isset;
  BOOL __pictype_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=driverid, setter=setDriverid:) int64_t driverid;
@property (nonatomic, getter=mobile, setter=setMobile:) int64_t mobile;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=score, setter=setScore:) int32_t score;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, retain, getter=drivercard, setter=setDrivercard:) NSString * drivercard;
@property (nonatomic, getter=driveage, setter=setDriveage:) int32_t driveage;
@property (nonatomic, retain, getter=province, setter=setProvince:) NSString * province;
@property (nonatomic, getter=drivercount, setter=setDrivercount:) int32_t drivercount;
@property (nonatomic, getter=state, setter=setState:) int32_t state;
@property (nonatomic, retain, getter=picture, setter=setPicture:) NSData * picture;
@property (nonatomic, getter=pictype, setter=setPictype:) int32_t pictype;
#endif

- (id) init;
- (id) initWithDriverid: (int64_t) driverid mobile: (int64_t) mobile name: (NSString *) name score: (int32_t) score longitude: (double) longitude latitude: (double) latitude drivercard: (NSString *) drivercard driveage: (int32_t) driveage province: (NSString *) province drivercount: (int32_t) drivercount state: (int32_t) state picture: (NSData *) picture pictype: (int32_t) pictype;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) driverid;
- (void) setDriverid: (int64_t) driverid;
#endif
- (BOOL) driveridIsSet;

#if !__has_feature(objc_arc)
- (int64_t) mobile;
- (void) setMobile: (int64_t) mobile;
#endif
- (BOOL) mobileIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) score;
- (void) setScore: (int32_t) score;
#endif
- (BOOL) scoreIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) drivercard;
- (void) setDrivercard: (NSString *) drivercard;
#endif
- (BOOL) drivercardIsSet;

#if !__has_feature(objc_arc)
- (int32_t) driveage;
- (void) setDriveage: (int32_t) driveage;
#endif
- (BOOL) driveageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) province;
- (void) setProvince: (NSString *) province;
#endif
- (BOOL) provinceIsSet;

#if !__has_feature(objc_arc)
- (int32_t) drivercount;
- (void) setDrivercount: (int32_t) drivercount;
#endif
- (BOOL) drivercountIsSet;

#if !__has_feature(objc_arc)
- (int32_t) state;
- (void) setState: (int32_t) state;
#endif
- (BOOL) stateIsSet;

#if !__has_feature(objc_arc)
- (NSData *) picture;
- (void) setPicture: (NSData *) picture;
#endif
- (BOOL) pictureIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pictype;
- (void) setPictype: (int32_t) pictype;
#endif
- (BOOL) pictypeIsSet;

@end

@interface Order : NSObject <NSCoding> {
  int32_t __orderid;
  int64_t __customermobile;
  NSString * __customername;
  int64_t __createtime;
  int64_t __pretime;
  NSString * __preaddress;
  int32_t __drivercount;
  int32_t __parentorderid;

  BOOL __orderid_isset;
  BOOL __customermobile_isset;
  BOOL __customername_isset;
  BOOL __createtime_isset;
  BOOL __pretime_isset;
  BOOL __preaddress_isset;
  BOOL __drivercount_isset;
  BOOL __parentorderid_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=orderid, setter=setOrderid:) int32_t orderid;
@property (nonatomic, getter=customermobile, setter=setCustomermobile:) int64_t customermobile;
@property (nonatomic, retain, getter=customername, setter=setCustomername:) NSString * customername;
@property (nonatomic, getter=createtime, setter=setCreatetime:) int64_t createtime;
@property (nonatomic, getter=pretime, setter=setPretime:) int64_t pretime;
@property (nonatomic, retain, getter=preaddress, setter=setPreaddress:) NSString * preaddress;
@property (nonatomic, getter=drivercount, setter=setDrivercount:) int32_t drivercount;
@property (nonatomic, getter=parentorderid, setter=setParentorderid:) int32_t parentorderid;
#endif

- (id) init;
- (id) initWithOrderid: (int32_t) orderid customermobile: (int64_t) customermobile customername: (NSString *) customername createtime: (int64_t) createtime pretime: (int64_t) pretime preaddress: (NSString *) preaddress drivercount: (int32_t) drivercount parentorderid: (int32_t) parentorderid;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) orderid;
- (void) setOrderid: (int32_t) orderid;
#endif
- (BOOL) orderidIsSet;

#if !__has_feature(objc_arc)
- (int64_t) customermobile;
- (void) setCustomermobile: (int64_t) customermobile;
#endif
- (BOOL) customermobileIsSet;

#if !__has_feature(objc_arc)
- (NSString *) customername;
- (void) setCustomername: (NSString *) customername;
#endif
- (BOOL) customernameIsSet;

#if !__has_feature(objc_arc)
- (int64_t) createtime;
- (void) setCreatetime: (int64_t) createtime;
#endif
- (BOOL) createtimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pretime;
- (void) setPretime: (int64_t) pretime;
#endif
- (BOOL) pretimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) preaddress;
- (void) setPreaddress: (NSString *) preaddress;
#endif
- (BOOL) preaddressIsSet;

#if !__has_feature(objc_arc)
- (int32_t) drivercount;
- (void) setDrivercount: (int32_t) drivercount;
#endif
- (BOOL) drivercountIsSet;

#if !__has_feature(objc_arc)
- (int32_t) parentorderid;
- (void) setParentorderid: (int32_t) parentorderid;
#endif
- (BOOL) parentorderidIsSet;

@end

@interface Comment : NSObject <NSCoding> {
  int64_t __mobile;
  int32_t __level;
  NSString * __message;
  int64_t __createtime;

  BOOL __mobile_isset;
  BOOL __level_isset;
  BOOL __message_isset;
  BOOL __createtime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=mobile, setter=setMobile:) int64_t mobile;
@property (nonatomic, getter=level, setter=setLevel:) int32_t level;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, getter=createtime, setter=setCreatetime:) int64_t createtime;
#endif

- (id) init;
- (id) initWithMobile: (int64_t) mobile level: (int32_t) level message: (NSString *) message createtime: (int64_t) createtime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) mobile;
- (void) setMobile: (int64_t) mobile;
#endif
- (BOOL) mobileIsSet;

#if !__has_feature(objc_arc)
- (int32_t) level;
- (void) setLevel: (int32_t) level;
#endif
- (BOOL) levelIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (int64_t) createtime;
- (void) setCreatetime: (int64_t) createtime;
#endif
- (BOOL) createtimeIsSet;

@end

@interface Appversion : NSObject <NSCoding> {
  double __version;
  NSString * __downurl;
  NSString * __remark;

  BOOL __version_isset;
  BOOL __downurl_isset;
  BOOL __remark_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=version, setter=setVersion:) double version;
@property (nonatomic, retain, getter=downurl, setter=setDownurl:) NSString * downurl;
@property (nonatomic, retain, getter=remark, setter=setRemark:) NSString * remark;
#endif

- (id) init;
- (id) initWithVersion: (double) version downurl: (NSString *) downurl remark: (NSString *) remark;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (double) version;
- (void) setVersion: (double) version;
#endif
- (BOOL) versionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) downurl;
- (void) setDownurl: (NSString *) downurl;
#endif
- (BOOL) downurlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) remark;
- (void) setRemark: (NSString *) remark;
#endif
- (BOOL) remarkIsSet;

@end

@interface Notification : NSObject <NSCoding> {
  int32_t __id;
  NSString * __title;
  int64_t __createtime;
  NSString * __message;

  BOOL __id_isset;
  BOOL __title_isset;
  BOOL __createtime_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, getter=createtime, setter=setCreatetime:) int64_t createtime;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithId: (int32_t) id title: (NSString *) title createtime: (int64_t) createtime message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (int64_t) createtime;
- (void) setCreatetime: (int64_t) createtime;
#endif
- (BOOL) createtimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@interface reportorder : NSObject <NSCoding> {
  int32_t __orderid;
  NSString * __paperid;
  NSString * __customername;
  NSString * __carno;
  int64_t __starttime;
  int64_t __endtime;
  int32_t __waitminutes;
  NSString * __startaddress;
  NSString * __endaddress;
  int32_t __distance;
  double __totalamount;
  double __vipamount;
  double __coupon;
  double __cash;
  BOOL __invoice;
  NSString * __remark;
  BOOL __complaint;
  int32_t __canceltype;
  int32_t __come;
  int64_t __pretime;

  BOOL __orderid_isset;
  BOOL __paperid_isset;
  BOOL __customername_isset;
  BOOL __carno_isset;
  BOOL __starttime_isset;
  BOOL __endtime_isset;
  BOOL __waitminutes_isset;
  BOOL __startaddress_isset;
  BOOL __endaddress_isset;
  BOOL __distance_isset;
  BOOL __totalamount_isset;
  BOOL __vipamount_isset;
  BOOL __coupon_isset;
  BOOL __cash_isset;
  BOOL __invoice_isset;
  BOOL __remark_isset;
  BOOL __complaint_isset;
  BOOL __canceltype_isset;
  BOOL __come_isset;
  BOOL __pretime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=orderid, setter=setOrderid:) int32_t orderid;
@property (nonatomic, retain, getter=paperid, setter=setPaperid:) NSString * paperid;
@property (nonatomic, retain, getter=customername, setter=setCustomername:) NSString * customername;
@property (nonatomic, retain, getter=carno, setter=setCarno:) NSString * carno;
@property (nonatomic, getter=starttime, setter=setStarttime:) int64_t starttime;
@property (nonatomic, getter=endtime, setter=setEndtime:) int64_t endtime;
@property (nonatomic, getter=waitminutes, setter=setWaitminutes:) int32_t waitminutes;
@property (nonatomic, retain, getter=startaddress, setter=setStartaddress:) NSString * startaddress;
@property (nonatomic, retain, getter=endaddress, setter=setEndaddress:) NSString * endaddress;
@property (nonatomic, getter=distance, setter=setDistance:) int32_t distance;
@property (nonatomic, getter=totalamount, setter=setTotalamount:) double totalamount;
@property (nonatomic, getter=vipamount, setter=setVipamount:) double vipamount;
@property (nonatomic, getter=coupon, setter=setCoupon:) double coupon;
@property (nonatomic, getter=cash, setter=setCash:) double cash;
@property (nonatomic, getter=invoice, setter=setInvoice:) BOOL invoice;
@property (nonatomic, retain, getter=remark, setter=setRemark:) NSString * remark;
@property (nonatomic, getter=complaint, setter=setComplaint:) BOOL complaint;
@property (nonatomic, getter=canceltype, setter=setCanceltype:) int32_t canceltype;
@property (nonatomic, getter=come, setter=setCome:) int32_t come;
@property (nonatomic, getter=pretime, setter=setPretime:) int64_t pretime;
#endif

- (id) init;
- (id) initWithOrderid: (int32_t) orderid paperid: (NSString *) paperid customername: (NSString *) customername carno: (NSString *) carno starttime: (int64_t) starttime endtime: (int64_t) endtime waitminutes: (int32_t) waitminutes startaddress: (NSString *) startaddress endaddress: (NSString *) endaddress distance: (int32_t) distance totalamount: (double) totalamount vipamount: (double) vipamount coupon: (double) coupon cash: (double) cash invoice: (BOOL) invoice remark: (NSString *) remark complaint: (BOOL) complaint canceltype: (int32_t) canceltype come: (int32_t) come pretime: (int64_t) pretime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) orderid;
- (void) setOrderid: (int32_t) orderid;
#endif
- (BOOL) orderidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) paperid;
- (void) setPaperid: (NSString *) paperid;
#endif
- (BOOL) paperidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) customername;
- (void) setCustomername: (NSString *) customername;
#endif
- (BOOL) customernameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) carno;
- (void) setCarno: (NSString *) carno;
#endif
- (BOOL) carnoIsSet;

#if !__has_feature(objc_arc)
- (int64_t) starttime;
- (void) setStarttime: (int64_t) starttime;
#endif
- (BOOL) starttimeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) endtime;
- (void) setEndtime: (int64_t) endtime;
#endif
- (BOOL) endtimeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) waitminutes;
- (void) setWaitminutes: (int32_t) waitminutes;
#endif
- (BOOL) waitminutesIsSet;

#if !__has_feature(objc_arc)
- (NSString *) startaddress;
- (void) setStartaddress: (NSString *) startaddress;
#endif
- (BOOL) startaddressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) endaddress;
- (void) setEndaddress: (NSString *) endaddress;
#endif
- (BOOL) endaddressIsSet;

#if !__has_feature(objc_arc)
- (int32_t) distance;
- (void) setDistance: (int32_t) distance;
#endif
- (BOOL) distanceIsSet;

#if !__has_feature(objc_arc)
- (double) totalamount;
- (void) setTotalamount: (double) totalamount;
#endif
- (BOOL) totalamountIsSet;

#if !__has_feature(objc_arc)
- (double) vipamount;
- (void) setVipamount: (double) vipamount;
#endif
- (BOOL) vipamountIsSet;

#if !__has_feature(objc_arc)
- (double) coupon;
- (void) setCoupon: (double) coupon;
#endif
- (BOOL) couponIsSet;

#if !__has_feature(objc_arc)
- (double) cash;
- (void) setCash: (double) cash;
#endif
- (BOOL) cashIsSet;

#if !__has_feature(objc_arc)
- (BOOL) invoice;
- (void) setInvoice: (BOOL) invoice;
#endif
- (BOOL) invoiceIsSet;

#if !__has_feature(objc_arc)
- (NSString *) remark;
- (void) setRemark: (NSString *) remark;
#endif
- (BOOL) remarkIsSet;

#if !__has_feature(objc_arc)
- (BOOL) complaint;
- (void) setComplaint: (BOOL) complaint;
#endif
- (BOOL) complaintIsSet;

#if !__has_feature(objc_arc)
- (int32_t) canceltype;
- (void) setCanceltype: (int32_t) canceltype;
#endif
- (BOOL) canceltypeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) come;
- (void) setCome: (int32_t) come;
#endif
- (BOOL) comeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) pretime;
- (void) setPretime: (int64_t) pretime;
#endif
- (BOOL) pretimeIsSet;

@end

@protocol DriverService <NSObject>
- (NSString *) login: (int64_t) driverid password: (NSString *) password;  // throws RuntimeError *, TException
- (int32_t) checkorder: (NSString *) sessionid;  // throws RuntimeError *, TException
- (Order *) acceptorder: (NSString *) sessionid orderid: (int32_t) orderid;  // throws RuntimeError *, TException
- (Driver *) getdriverdetail: (NSString *) sessionid driverid: (int64_t) driverid;  // throws RuntimeError *, TException
- (NSString *) setlocation: (NSString *) sessionid longitude: (double) longitude latitude: (double) latitude address: (NSString *) address;  // throws RuntimeError *, TException
- (NSString *) setstate: (NSString *) sessionid state: (int32_t) state;  // throws RuntimeError *, TException
- (NSString *) createorderbycall: (NSString *) sessionid callmobile: (int64_t) callmobile;  // throws RuntimeError *, TException
- (NSMutableArray *) getorderlist: (NSString *) sessionid state: (int32_t) state;  // throws RuntimeError *, TException
- (NSMutableDictionary *) getincome: (NSString *) sessionid;  // throws RuntimeError *, TException
- (NSMutableArray *) getcomment: (NSString *) sessionid pageindex: (int32_t) pageindex driverid: (int64_t) driverid;  // throws RuntimeError *, TException
- (NSMutableArray *) getneardrivers: (NSString *) sessionid count: (int32_t) count distance: (int32_t) distance;  // throws RuntimeError *, TException
- (NSString *) uporder: (NSString *) sessionid order: (reportorder *) order;  // throws RuntimeError *, TException
- (NSString *) cancleorder: (NSString *) sessionid order: (reportorder *) order;  // throws RuntimeError *, TException
- (NSString *) makeuporder: (NSString *) sessionid order: (reportorder *) order;  // throws RuntimeError *, TException
- (NSMutableArray *) getnotification: (NSString *) sessionid pageindex: (int32_t) pageindex;  // throws RuntimeError *, TException
- (NSString *) startorder: (NSString *) sessionid orderid: (int32_t) orderid longitude: (double) longitude latitude: (double) latitude address: (NSString *) address orderstate: (int32_t) orderstate;  // throws RuntimeError *, TException
- (NSMutableArray *) finddrivers: (double) longitude latitude: (double) latitude count: (int32_t) count distance: (int32_t) distance;  // throws RuntimeError *, TException
- (NSString *) getvalidatecode: (int64_t) mobile;  // throws RuntimeError *, TException
- (Order *) orderdrivers: (int64_t) mobile address: (NSString *) address reachtime: (int32_t) reachtime count: (int32_t) count;  // throws RuntimeError *, TException
- (NSMutableArray *) getdrviercomment: (int32_t) driverid;  // throws RuntimeError *, TException
- (NSString *) recharge: (int64_t) code mobile: (int64_t) mobile;  // throws RuntimeError *, TException
- (NSMutableDictionary *) getcitylist;  // throws RuntimeError *, TException
- (NSMutableDictionary *) getpricelist: (int32_t) city;  // throws RuntimeError *, TException
- (NSMutableArray *) getcustomerorders: (NSString *) sessionid pageindex: (int32_t) pageindex;  // throws RuntimeError *, TException
- (NSString *) sendsuggestion: (int32_t) type message: (NSString *) message;  // throws RuntimeError *, TException
- (Appversion *) checkversion: (int32_t) clienttype currversion: (double) currversion;  // throws RuntimeError *, TException
- (NSString *) sendsms: (int64_t) mobile message: (NSString *) message;  // throws RuntimeError *, TException
- (NSData *) decryptpicture: (NSString *) sessionid opicture: (NSData *) opicture apitype: (int32_t) apitype;  // throws RuntimeError *, TException
@end

@interface DriverServiceClient : NSObject <DriverService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface DriverServiceProcessor : NSObject <TProcessor> {
  id <DriverService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithDriverService: (id <DriverService>) service;
- (id<DriverService>) service;
@end

@interface zuoxinConstants : NSObject {
}
@end
